homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customize


# Enables the frontend
frontend:

# Enable ios
ios:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_cert
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
  exclude:
    entities:
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state
      - sensor.yr_cloudiness
      - sensor.yr_precipitation
      - sensor.yr_symbol
      - sensor.yr_wind_direction
      - sensor.yr_wind_speed

dweet:
  name: secret dweet_name
  whitelist:
    - sensor.ute_temperature

# View all events in a logbook
logbook:

# Track the sun
sun:

# Rfxcom hub
rfxtrx:
  device: /dev/ttyUSB0

# Text to speech
tts:
  platform: google
  language: 'sv'

# Test
cover:
  - platform: rfxtrx
    automatic_add: True

#Imports

light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
media_player: !include_dir_merge_list mediaplayers
binary_sensor: !include_dir_merge_list binary_sensors
group: !include groups.yaml
automation: !include_dir_merge_list automation
input_select: !include_dir_merge_named input_selects

# Zones

zone 1:
  name: !secret school_name
  latitude: !secret school_lat
  longitude: !secret school_long
  radius: 100
  icon: mdi:school

zone 2:
  name: !secret work_name
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 400
  icon: mdi:worker
